name: ghostty_vte
description: "Dart/Flutter FFI bindings for libghostty-vt."
version: 0.0.1

environment:
  sdk: ^3.10.4

resolution: workspace

dependencies:
  code_assets: ^1.0.0
  hooks: ^1.0.1
  ffi: ^2.2.0

dev_dependencies:
  ffigen: ^20.1.1
  flutter_lints: ^6.0.0
  test: ^1.25.8
