name: dart_terminal_workspace
publish_to: none

environment:
  sdk: ^3.10.4

workspace:
  - pkgs/vte/ghostty_vte
  - pkgs/vte/ghostty_vte/example
  - pkgs/vte/ghostty_vte_flutter
  - pkgs/pty/portable_pty
  - pkgs/pty/portable_pty_flutter
